#! /usr/bin/bash
echo snakemake --nolock -s /opt/assembly-scripts/atoms.smk -p -c 1 "$@"
# option -c 1 can be overriden in the argument
snakemake --nolock -s /opt/assembly-scripts/atoms.smk -p -c 1 "$@"
